## Statistical Ananlyses of regulator co-occurrence in bacterial genomes

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/hdd/projects/erc_project/data/filtered_regulators.csv', delimiter = ',')

In [4]:
df

,Unnamed: 0,35EXOc,3a0106s01,3a0107s01c2,3a01204,3a01205,3a01208,49,AAA,AAA_2,...,YkoV,YmfN,YncA,YnjD,YufO,zf-CHC2,Zn_ribbon_recom,ZnF_CHCC,znuC,ZnuC
0,AY129331,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AY129338,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,BA000030,0,1,1,1,2,1,0,6,1,...,0,0,1,1,2,0,0,0,1,1
3,DQ398041,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,EU816588,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,MN096381,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
269,MN096382,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
270,phiSco2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
271,phiSco3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
272,phiSven3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0